# Generated by Django 2.1.1 on 2019-05-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190512_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_info', to='game.Game'),
        ),
    ]
